import type { Hero } from './heroTypes.js';

//
// AUTO-GENERATED by scripts/hero-sync/sync.ts.
// Review the generated PR; do not edit relationship data here.
//
const autoSyncedHeroes: Hero[] = [
  {
    "id": 118,
    "englishName": "Flowborn (Assassin)",
    "chineseName": "Coming soon",
    "occupation": "Jungling",
    "altOccupation": "",
    "campId": 583,
    "imageLink": "/heroesImg/118.png",
    "combo": [],
    "counter": [],
    "beCountered": [],
    "relationshipStatus": "unverified",
    "variantGroup": "flowborn"
  },
  {
    "id": 119,
    "englishName": "Flowborn (Roamer)",
    "chineseName": "Coming soon",
    "occupation": "Roaming",
    "altOccupation": "",
    "campId": 585,
    "imageLink": "/heroesImg/119.png",
    "combo": [],
    "counter": [],
    "beCountered": [],
    "relationshipStatus": "unverified",
    "variantGroup": "flowborn"
  }
];

export default autoSyncedHeroes;
