import type { Hero } from './heroTypes.js';

//
// AUTO-GENERATED by scripts/hero-sync/sync.ts.
// Review the generated PR; do not edit relationship data here.
//
const autoSyncedHeroes: Hero[] = [
  {
    "id": 118,
    "englishName": "Flowborn (Assassin)",
    "chineseName": "Coming soon",
    "occupation": "Jungling",
    "altOccupation": "",
    "campId": 583,
    "imageLink": "/heroesImg/118.png",
    "combo": [],
    "counter": [],
    "beCountered": [],
    "relationshipStatus": "unverified",
    "variantGroup": "flowborn"
  },
  {
    "id": 119,
    "englishName": "Flowborn (Roamer)",
    "chineseName": "Coming soon",
    "occupation": "Roaming",
    "altOccupation": "",
    "campId": 585,
    "imageLink": "/heroesImg/119.png",
    "combo": [],
    "counter": [],
    "beCountered": [],
    "relationshipStatus": "unverified",
    "variantGroup": "flowborn"
  },
  {
    "id": 120,
    "englishName": "Wang Wei",
    "chineseName": "王维",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "campId": 138,
    "imageLink": "https://world.honorofkings.com/zlkdatasys/ip/hero/en//image/20260914/17893719635393.png",
    "recognitionImageLink": "https://world.honorofkings.com/zlkdatasys/ip/hero/en//image/20260914/17893719635393.png",
    "iconCrop": {
      "x": 62,
      "y": 36,
      "scale": 1.65
    },
    "artLink": "https://world.honorofkings.com/zlkdatasys/ip/hero/en//image/20260916/17895496027563.jpg",
    "combo": [],
    "counter": [],
    "beCountered": [],
    "relationshipStatus": "unverified"
  }
];

export default autoSyncedHeroes;
